name: Build TWRP for Samsung Galaxy A71

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180 # 3-hour timeout (adjust if needed)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set Up Environment
      run: |
        sudo apt update -y
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 python-is-python3

    - name: Set Up Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Clone TWRP Manifest
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

    - name: Copy Device Tree
      run: |
        mkdir -p ~/twrp/device/samsung/a71
        cp -r $GITHUB_WORKSPACE/* ~/twrp/device/samsung/a71/

    - name: Build TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_a71-eng
        mka recoveryimage

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-Recovery-A71
        path: ~/twrp/out/target/product/a71/recovery.img
