name: Build TWRP for Samsung A71

on: push: branches: - main pull_request: branches: - main

env: BUILD_ROOT: ${{ github.workspace }}/android TWRP_BRANCH: twrp-12.1 DEVICE_TREE_REPO: https://github.com/mehedihjoy0/twrp_samsung_a71.git DEVICE_CODENAME: a71 MAKE_THREADS: ${{ runner.cores }} USE_CCACHE: "1" CCACHE_MAXSIZE: 10G

jobs: build: name: Build TWRP Recovery runs-on: ubuntu-latest

steps:
- name: Checkout Device Tree
  uses: actions/checkout@v3
  with:
    repository: mehedihjoy0/twrp_samsung_a71
    path: device/samsung/${{ env.DEVICE_CODENAME }}

- name: Install Dependencies
  run: |
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
      openjdk-11-jdk-core git-core gnupg flex bison gperf build-essential \
      zip curl zlib1g-dev gcc-multilib g++-multilib \
      libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
      libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc \
      unzip python3

- name: Setup Repo Tool
  run: |
    mkdir -p ~/bin
    curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
    echo "export PATH=~/bin:$PATH" >> $GITHUB_ENV

- name: Initialize AOSP for TWRP
  run: |
    mkdir -p $BUILD_ROOT
    cd $BUILD_ROOT
    repo init -u https://github.com/TeamWin/android_bootable_recovery.git -b $TWRP_BRANCH
    repo sync -c -j$(nproc) --no-tags --no-clone-bundle

- name: Copy Device Tree
  run: |
    rsync -a --exclude='.git*' $GITHUB_WORKSPACE/device/samsung/${DEVICE_CODENAME} $BUILD_ROOT/device/samsung/

- name: Setup Environment
  run: |
    cd $BUILD_ROOT
    source build/envsetup.sh
    export USE_CCACHE=$USE_CCACHE
    ccache -M $CCACHE_MAXSIZE

- name: Lunch TWRP
  run: |
    cd $BUILD_ROOT
    lunch recovery_${DEVICE_CODENAME}-eng

- name: Build Recovery
  run: |
    cd $BUILD_ROOT
    make -j${MAKE_THREADS} recoveryimage

- name: Upload TWRP Image
  uses: actions/upload-artifact@v3
  with:
    name: TWRP-recovery-${{ env.DEVICE_CODENAME }}
    path: $BUILD_ROOT/out/target/product/${DEVICE_CODENAME}/recovery.img

